name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  format-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: [20, 21, 22, 23, 24, 25]
        elixir: ["1.9.4", "1.10.4", "1.11.4", "1.12.3", "1.13.4"]
        exclude:
          - elixir: "1.9.4"
            otp: 23
          - elixir: "1.9.4"
            otp: 24
          - elixir: "1.9.4"
            otp: 25
          - elixir: "1.10.4"
            otp: 20
          - elixir: "1.10.4"
            otp: 24
          - elixir: "1.10.4"
            otp: 25
          - elixir: "1.11.4"
            otp: 20
          - elixir: "1.11.4"
            otp: 25
          - elixir: "1.12.3"
            otp: 20
          - elixir: "1.12.3"
            otp: 21
          - elixir: "1.12.3"
            otp: 25
          - elixir: "1.13.4"
            otp: 20
          - elixir: "1.13.4"
            otp: 21
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: actions/cache@v2
        id: cache-build-elixir-deps
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: build elixir deps
        if: steps.cache-build-elixir-deps.outputs.cache-hit != 'true'
        env:
          MIX_ENV: test
        run: mix do deps.get, deps.compile

      - name: run format checker
        run: mix format --check-formatted
      - name: run tests
        run: mix test
